---
# -|----------------------------------------------------------------------------
#  | VPN Settings
# -|----------------------------------------------------------------------------
#  |     - `vpn_server` is the IP address/hostname of the server (there sould be
#  |       a directory called algo/configs/${{ vpn_server }})
#  |     - `vpn_user`  is the name of the user that the Pi should connect as.
#  |
vpn_server:
vpn_user: pi

# -|----------------------------------------------------------------------------
#  | Device Settings
# -|----------------------------------------------------------------------------
#  |  Set the hardware adapters here
#  |     - `wifi_adapter` is the device which will be used to create a wifi network
#  |     - `lan_adapter`  is the device that is connected to the internet
#  |
wifi_adapter: wlan0
wireguard_adapter: wg0


# -|----------------------------------------------------------------------------
#  | Static IP settings for the lan_adapter
# -|----------------------------------------------------------------------------
#  |  If you want the lan_adapter (the one connecting your access point to a
#  |  router) to have a fixed ip address, you can configure this here.
#  |     - `enabled` set this to `True` to enable static ip configuration
#  |     - `address` the ip address of the adapter
#  |     - `netmask` the corresponding subnet mask
#  |     - `gateway` ip address of the router
#  |
lan_static:
  enabled: True
  address: 192.168.0.2
  netmask: 255.255.255.0
  gateway: 192.168.0.1


# -|----------------------------------------------------------------------------
#  | Wifi Settings
# -|----------------------------------------------------------------------------
#  |  Configuration options for your access point.
#  |
#  |     `ssid`: the "name" of the wifi networks as it appears in the
#  |             list of available networks on client devices
#  |
#  |     `channel`: the wifi channel that will be used
#  |
#  |     `security.enabled`: set to `True` to enable WPA-2 encryption
#  |     `security.psk`: the "password" for the network
#  |                     (ignored if security.enabled == False)
#  |
ssid: erfindergarden-2
channel: 6

security:
  enabled: True
  psk: albert-einstein  # The "password" for the network (at least 8 characters)


# -|----------------------------------------------------------------------------
#  | DHCP Settings
# -|----------------------------------------------------------------------------
#  |  Settings for the local dhcp server. Configure
#  |  address range, gateway, etc. here.
#  |
#  |
ip_base: 192.168.4
own_ip: "{{ ip_base }}.1"
ip_range:
  start: "{{ ip_base }}.2"
  end: "{{ ip_base }}.20"
dns_servers: "192.168.0.1 8.8.8.8 4.4.4.4"
subnet_mask: 255.255.255.0
network: "{{ ip_base }}.0"
broadcast: "{{ ip_base }}.255"
lease_time: 864000  # That's how many seconds are in 10 days


# -|----------------------------------------------------------------------------
#  | Tweaks
# -|----------------------------------------------------------------------------
#  |  Some advanced options for special cases
#  |
#  |     `disable_wmm`: Set to `True` to disable QoS
#  |
disable_wmm: false
