---
# -|----------------------------------------------------------------------------
#  | VPN Settings
# -|----------------------------------------------------------------------------
#  |     - `vpn_server` is the IP address/hostname of the server (there sould be
#  |       a directory called algo/configs/${{ vpn_server }})
#  |     - `vpn_user`  is the name of the user that the Pi should connect as.
#  |
vpn_server:
vpn_user: pi

# -|----------------------------------------------------------------------------
#  | Device Settings
# -|----------------------------------------------------------------------------
#  |  Set the hardware adapters here
#  |     - `wifi_adapter` is the device which will be used to create a wifi network
#  |     - `lan_adapter`  is the device that is connected to the internet
#  |
wifi_adapter: wlan0
wireguard_adapter: wg0


# -|----------------------------------------------------------------------------
#  | Wifi Settings
# -|----------------------------------------------------------------------------
#  |  Configuration options for your access point.
#  |
#  |     `country_code` : regulatory domain, using https://en.wikipedia.org/wiki/ISO_3166-1
#  |     `ssid`: the "name" of the wifi networks as it appears in the
#  |             list of available networks on client devices
#  |
#  |     `security.enabled`: set to `True` to enable WPA-2 encryption
#  |     `security.psk`: the "password" for the network
#  |                     (ignored if security.enabled == False)
#  |
ssid: erfindergarden-2

country_code: CH

psk: nope  # The "password" for the network (at least 8 characters)


# -|----------------------------------------------------------------------------
#  | DHCP Settings
# -|----------------------------------------------------------------------------
#  |  Settings for the local dhcp server. Configure
#  |  address range, gateway, etc. here.
#  |
#  |
ip_base: 192.168.4
own_ip: "{{ ip_base }}.1"
ip_range:
  start: "{{ ip_base }}.2"
  end: "{{ ip_base }}.20"
subnet_mask: 255.255.255.0
