
---
- name: Setup {{ target }} as a Wireguard client
  hosts: "{{ target }}"
  become: yes
  roles:
    - role: wireguard-client
      tags: wireguard-client
      vars:
        wireguard_conf_local_path: "algo/configs/{{ vpn_server }}/wireguard/{{ vpn_user }}.conf"
