---
# Installs and sets up wireguard.
# Requires wireguard_conf_local_path to be set.
#
# https://github.com/trailofbits/algo/blob/master/docs/client-linux-wireguard.md

# Without this task, `apt update` fails with `The following signatures couldn't
# be verified because the public key is not available: NO_PUBKEY
# 04EE7237B7D453EC NO_PUBKEY 648ACFD622F3D138`.
#
# Why the fuck is the keyserver on ubuntu.com? How the fuck are you supposed to
# figure this out? Why the fuck isn't they keyring packaged with Debian? Who the
# fuck knows. I fucking hate computers. Debian and Ansible are both fractals of
# nightmarish fuckery.
- name: Add keys for reading from backports repo
  with_items:
    - E0B11894F66AEC98
    - DC30D7C23CBBABEE
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ item }}"
- name: Add backports repo
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
    filename: backports-wireguard
    update_cache: false
# Without this task, kernel headers aren't installed which means the
# wireguard-dkms package doesn't install the wireguard kmod. AFAICT this
# Raspbian being crap.
- name: Install kernel headers
  apt:
    name: raspberrypi-kernel-headers
    state: present
- name: Install wireguard & openresolv
  apt:
    name: [openresolv, wireguard]
    state: present
- name: Install wireguard configuration
  copy:
    src: "{{ wireguard_conf_local_path | mandatory }}"
    dest: /etc/wireguard/wg0.conf
    owner: root
    mode: 0600
- name: (Re)start & enable wireguard service
  systemd:
    name: wg-quick@wg0
    state: restarted # Always restarts service
    enabled: yes     # Start it on boot too

