---
# https://www.raspberrypi.org/documentation/configuration/wireless/access-point-routed.md

- name: Install required software packages
  apt:
    name:
      - hostapd
      - dnsmasq
      - iptables-persistent  # auto-loads iptables rules on boot
      - netfilter-persistent
    state: present

# The repo I forked this from did it directly in /etc/network/interfaces. Here
# instead we leave dhcpcd running and just tell _that_ to add a static
# interface. Not too sure what the pros/cons of these two approaches are but I'm
# following the version from raspberrypi.org.
- name: Assign static IP to wireless interface
  template:
    src: templates/dhcpcd.j2
    dest: /etc/dhcpcd.conf
